### PR TITLE
chore: add eslint with standard configuration + react plugin

### PR DESCRIPTION
**Pull request by ptbrowne**
ESLint enables lint warning while you are developing so you are not frustrated when you `yarn build` and you find out there are `standard` errors. It also can catch other bugs like [`React` not being defined while you use JSX](https://github.com/cozy/cozy-ui/pull/108#issuecomment-302328176 ).

image

### CODE REVIEW

**Comment by enguerran** [comment]
@ptbrowne @gregorylegarec 
How does it relate with `standardjs` already existing in this project to avoid `eslint` configuration file?

**Comment by ptbrowne** [comment]
@enguerran standard by default does not have rules for JSX.

I changed the .eslint config file to rely on `eslint-config-standard-react` which remove complexity from the config file.

**Comment by CPatchane** [comment]
Thanks @ptbrowne 👍

**Comment by enguerran** [comment]
Why? We use to use `standardjs` which includes https://www.npmjs.com/package/eslint-config-standard-react. And now we depend also on https://www.npmjs.com/package/eslint-plugin-react? Could you justify your commits and the merges?

I cannot understand how it becomes better than what we use to have.

**Comment by ptbrowne** [comment]
Maybe I made a mistake but when I started on the `cozy-edf` app, there was no linting when you saved the file. What I was experiencing was that when I wanted to build, I had linting errors. To me, it is a better developer experience when you have the linter error when you type since you can correct your error right away.

Also `standardjs` never warned me about `React` not being defined while I used JSX. 

For example with this code : 

```jsx
export default function () {
  return <div>Hello world !</div>
}
```

I would have no build error until I tested my code in production and it crashed since the JSX was transpiled to `React.createElement` snippets and React was not defined. This is why `eslint-config-standard-react` is useful since it can detects this kind of error.

It can also help you with performance since it can detect `.bind()` being used in `render` funcs.

>  We use to use standardjs which includes https://www.npmjs.com/package/eslint-config-standard-react.

I had not this impression since I did not get any lint error concerning `React`.

**Comment by enguerran** [comment]
There ain't a problem with standardjs or eslint, I think you did not add the correct plugin into your code editor. We all work on JavaScript code with React and JSX since a a while and noone has a linter's deficit in their code editor. Noone have thought we need to migrate from standardjs to eslint (the most because standardjs is eslint with fixed rules, if I am correct).

That is way I do not understand this PR. Maybe @m4dz @gregorylegarec or @CPatchane could explain me what the needs are?

**Comment by gregorylegarec** [comment]
@enguerran @ptbrowne I did not understand that we were removing standardjs with this PR, only improving our linting for React. My bad. We should rollback IMHO. Thanks @enguerran.

**Comment by CPatchane** [comment]
Same as @gregorylegarec, I just thinking about a tools improvement, very sorry for that. I can understand the @ptbrowne needs here but I never notice this kind of failures on my side as @enguerran said. Maybe we can recommend some atom packages to work with the cozy application environment and avoid all that.

**Comment by ptbrowne** [comment]
> @enguerran @ptbrowne I did not understand that we were removing standardjs with this PR, only improving our linting for React.

For the record, I am not advocating for removing `standard`. It was only to have the linting errors when developing in the console.

> We all work on JavaScript code with React and JSX since a a while and noone has a linter's deficit in their code editor. 

I understand better. I usually rely on linting errors in the console not in my editor as it means that every contributor does not have to add plugins to his own editor.

> Maybe we can recommend some atom packages to work with the cozy application environment and avoid all that.

Yes, yes I think that's the way to go if you are used to rely on your editor's errors.

> We should rollback IMHO.

Should I do another PR to do that or revert in this one ?

**Comment by enguerran** [comment]
The developer's editor is its primary tool. He and she uses it every day and since Sublime Text, he and she could fully customizes it as he and she wants.

In other hand, we put npm scripts to make specific tasks regarding our wanted workflow. As you can see here: https://github.com/cozy/cozy-template/blob/master/.templates/package.json#L6-L39. Those scripts are also used by our continuous integration tool, especially this line: https://github.com/cozy/cozy-template/blob/master/.templates/package.json#L23.

> "lint:js": "standard 'src/\*\*/\*.js' 'src/\*\*/\*.jsx' 'test/\*\*/\*.js' 'mobile/src/\*\*/\*.js' 'mobile/src/\*\*/\*.jsx' 'mobile/test/\*\*/\*.js'"

As explain earlier, standard will ignore any `.eslintrc` configuration files. Then, if you need to customize your editor, you should configure it without changing anything in the continuous integration workflow. But be ware that your development environment's setup will differ from the continuous integration's one.

**Comment by gregorylegarec** [comment]
@enguerran I tried this configuration on Cozy-Collect but did not encounter any particular issue. What is bothering you ?

**Comment by enguerran** [comment]
What is bothering me is that using standard is our choice to avoid discussion on linters. Adding eslint for editors only is a anti-pattern as `yarn lint:js` will not use eslint configuration file. We made choices and we add noise in our template's configuration.

This said, I do not want to argue any further. And I accept this PR, the introduction of custom eslint rules in addition to standard configuration.

**Comment by gregorylegarec** [comment]
@enguerran Ok I see and understand your point. Editors linters should be every developer's concern and should not be added to repository, especially when we already have a lint task. Do I get it correctly ?
With your response, I think that I prefer to avoid providing an editor linter in our templates. But maybe someone may have another opinion. @m4dz ? @goldoraf ? @y-lohse ?

**Pull request merged**
