### PR TITLE
Refactoring template

### PR DESCRIPTION
**Pull request by Peltoche**
- Add ViewCollection class
- Add a basic exemple which use almost all basic classes
- Good with lint (one little error with one for loop)

### CODE REVIEW

**Comment by clochix** [comment]
Thanks @Peltoche. @jsilvestre would you mind reviewing this, please ?

**Comment by frankrousseau** [comment]
@kelukelu can you make a new icon for the default application?

**Comment by kelukelu** [comment]
screen shot 2015-09-21 at 12 24 56
@Peltoche @clochix @frankrousseau: Good for you guys ?

**Comment by Peltoche** [comment]
Yeah! That's cool!

**Comment by kelukelu** [comment]
Find the svg [here](https://luc.cozycloud.cc/public/files/files/109be9814f75b8239eab6c4d03a235d0/attach/template.svg)

**Comment by frankrousseau** [comment]
@Peltoche can you include the icon from @kelukelu ?

**Comment by clochix** [comment]
Ping @Peltoche : could you include the icon and rebase your work or fix the conflicts ?

**Comment by Peltoche** [comment]
Afterlook my template need some work so I close the PR and will make a new one when this will be ready

**Pull request closed without merging**
